[package]
name = "proka-kernel"
version = "0.1.0"
edition = "2024"

[build-dependencies]
glob = "0.3.0"

[dependencies]
multiboot2 = { workspace = true }
x86_64 = { workspace = true }
lazy_static = { workspace = true }
paste = { workspace = true }
uart_16550 = { workspace = true }
spin = { workspace = true }

