title = "Memory Manager"

[[config]]
name = "KERNEL_DEFAULT_HEAP_SIZE"
type = "int"
default = 8388608
desc = "The size of the heap memory (Unit: Bytes)."

[[config]]
name = "PAGE_SIZE"
type = "int"
default = 4096
desc = "The Page Size (Unit: Bytes)."
